version: "3.1"

services:
  coderhouse-mongodb:
    image: mongo:4
    container_name: coderhouse-mongodb
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
